// <auto-generated />
namespace ClothBazar.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addcolors : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcolors));
        
        string IMigrationMetadata.Id
        {
            get { return "202005261507103_addcolors"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
